#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

#!/usr/bin/env bash
# install nginx to create html pages
apt-get -y update
apt-get -y install nginx
echo "Hello World" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
