#!/usr/bin/env bash
# Displays information about the file `holbertonschool`.
if [ -e "holbertonschool" ]
then
  echo "holbertonschool file exists"
  if [ -s "holbertonschool" ]
  then
    echo "holbertonschool file is not empty"
  else
    echo "holbertonschool file is empty"
  fi
  if [ -f "school" ]
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi